name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_BASE_NAME: ${{ toLower(github.repository) }}

jobs:

  build:

    runs-on: ubuntu-latest

    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      # Build Docker images
      - name: Build the Backend Docker image
        run: docker build ./backend --file ./backend/Dockerfile.prod --tag ${{ env.REGISTRY }}/${{ env.IMAGE_BASE_NAME }}/backend:$(date +%s)
      - name: Build the Frontend Docker image
        run: docker build ./frontend --file ./frontend/Dockerfile.prod --tag ${{ env.REGISTRY }}/${{ env.IMAGE_BASE_NAME }}/frontend:$(date +%s)

      # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
      - name: Log in to the Container registry
        if: github.event_name == 'push'
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Push Docker images
      - name: Push the Backend Docker image
        if: github.event_name == 'push'
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_BASE_NAME }}/backend:$(date +%s)
      - name: Push the Frontend Docker image
        if: github.event_name == 'push'
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_BASE_NAME }}/frontend:$(date +%s)
